User story 17 remove shifts
Hold-A-sys-projekt/generisk_vagtplan_ pull request #15
Opened 2024-05-11 19:25 UTC by Toebzy

2024-05-14 08:06 UTC, Sebbedeb requested changes
Det ser godt ud, men I må ikke lægge package-lock op. Den må I gerne lige tilføje til gitignore og så lave en ny PR

2024-05-17 21:44 UTC, Peter537 reviewed
I har slettet nogle ting som jeg ikke lige er 100% sikker på hvorfor I har gjort det, kan I evt. smide en besked på discord eller noget i den stil?

2024-05-17 21:44 UTC, Peter537 commented on backend/generisk_vagtplan_backend/src/main/java/dat/controller/EmployeeController.java
Hvorfor bliver denne metode (og routing) fjernet?

Denne metode bliver brugt i (mindst) en anden user story, så hvis det er fordi I har tænkt den skulle erstattes med noget andet, så må I gerne lige sende en besked til os

2024-05-17 21:44 UTC, Peter537 commented on .github/workflows/enforcer.yml
En grund til denne er fjernet?

2024-05-18 13:58 UTC, Toebzy commented on .github/workflows/enforcer.yml
Det er ikke noget vi selv har fjernet, så er faktisk ikke sikker på hvorfor

2024-05-18 14:13 UTC, Toebzy commented on backend/generisk_vagtplan_backend/src/main/java/dat/controller/EmployeeController.java
Vi forstod det som at vi skulle skifte til at bruge UserController og UserRoutes, ud fra Yusef's besked. Så vi har ikke slettet det, men rykket det.

2024-05-22 11:19 UTC, merged