Us20 shift sale frntnd
Hold-A-sys-projekt/generisk_vagtplan_ pull request #34
Opened 2024-05-23 12:12 UTC by havvand

Final version for User Story 20 - Frontend.

**1. ShiftforSale page done.** 
 - Shiftsale.jsx logic for Manager or Employee needs implementation from backend.
 - Minor fixes to User,  Role and Shift Entity due to infinit recursion.
 
**2. Set shift for sale Button on Calendar-page done.**
 - Atm acces to specific user is through URL.

2024-05-23 13:04 UTC, Sebbedeb requested changes
Merge dev ind i jeres branch, fix merge conflicts og prøv igen :)

2024-05-23 14:16 UTC, havvand commented
Dev er merged!

2024-05-23 16:23 UTC, Peter537 commented on backend/generisk_vagtplan_backend/src/main/java/dat/config/HibernateConfig.java
> +            properties.put("hibernate.connection.url", "jdbc:postgresql://localhost:");
db navn og port slettet?

2024-05-23 16:23 UTC, Peter537 commented on backend/generisk_vagtplan_backend/src/main/java/dat/route/ShiftRoutes.java
> +                    get("/id", shiftController::getById);
Jeg ved der allerede er folk/websider som bruger endpointet /shifts/{id}, kan I revert til uden /id bagpå

2024-05-23 17:22 UTC, havvand commented on backend/generisk_vagtplan_backend/src/main/java/dat/config/HibernateConfig.java
> +            properties.put("hibernate.connection.url", "jdbc:postgresql://localhost:");
Der blev anvendt forskellige navne på db i teamet, så fjernede det. I smider bare på hvad i ønsker.

2024-05-23 17:36 UTC, havvand commented on backend/generisk_vagtplan_backend/src/main/java/dat/route/ShiftRoutes.java
> +                    get("/id", shiftController::getById);
Hvis det er den kun med /id bagpå, så mener jeg det godt kan lade sig gøre. Det er Williams kode, og jeg ved han havde problemer med at få den gældende route til at virke korrekt, derfor blev der tilføjet /id. Har bedt William om at tage fat på jer.

I mellemtiden kan i bare fjerne den linje og så må William rette ind.

2024-05-23 19:13 UTC, Peter537 approved these changes

2024-05-24 07:57 UTC, Sebbedeb approved these changes

2024-05-24 07:58 UTC, merged